[package]
name = "runner"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cairo-args-runner.workspace = true
clap.workspace = true
lalrpop-util.workspace = true
regex = "1.10.3"
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
lalrpop.workspace = true
